### ISSUE TITLE
dynamic global context?

### ISSUE THREAD

**Issue by turtleDev** [hapijs/vision#100]
Hi,

I'd like to have a dynamic global context for rendering some page elements. This context applies to a lot of different views, hence I'd rather not pass it around manually. `vision` supports a static global context, but no dynamic context, that could change during the execution of the program. 

I did hack around a little using request hooks, but that is barely a solution. Would you be open to a patch that adds this feature ?

**Comment by calmdev** [comment]
How is using a server extension point to provide additional context to your views barely a solution? A code example demonstrating your pain point(s) would be helpful to better understand.

When you're setting up the view manager you can access the request object to dynamically inject additional context into your views. For example, if you use an `onRequest` extension point to add your _global  page element context_ onto the request object you should be able to access that from your views by passing along the request using the `context` option.

```js
server.views({
  engines: { 
   dust: require('dustjs-linkedin'),
  },
  // Set view paths.
  path: '/path/to/views',
  // Make request object available to every view context.
  context: function(request) {

    return { request };
  }
});
```

**Comment by turtleDev** [comment]
ahh perfect. talk about hiding in plain sight. This is exactly what I needed. Thank you!
