### ISSUE TITLE
Dependencies update required

### ISSUE THREAD

**Issue by FullStackForger** [hapijs/vision#102]
could we just use Hoek 4.1.0 instead of 3.0.4

```
`-- vision@4.1.0
  +-- boom@3.2.2
  | `-- hoek@4.1.0
  +-- hoek@3.0.4                        <--          ???
  `-- joi@8.4.2
    `-- hoek@4.1.0                        <--            ???
```

**Comment by fullstackforger** [comment]
I have just checked package.json and it looks ok.
```
  "dependencies": {
    "boom": "3.x.x",
    "hoek": "4.x.x",
    "items": "2.x.x",
    "joi": "8.x.x"
  },
```
However package.json in local file system after npm install vision is
```
  "dependencies": {
    "boom": "3.x.x",
    "hoek": "3.x.x",
    "items": "2.x.x",
    "joi": "8.x.x"
  },
```

Did we miss `npm publish` for 4.1.0 ? If yes can we update it please.

**Comment by sholladay** [comment]
This issue can be closed. All of the dependencies are up to date here, both  in the `master` branch and the latest published to `npm`.

Any out of date dependencies are merely happening on your local machine. Probably you just need to `rm -rf node_modules && npm install` and if that doesn't work then your `npm` is buggy. In the latter case, run `npm install -g npm` and try again.

**Comment by AdriVanHoudt** [comment]
@fullstackforger can you run `-rf node_modules && npm install` and verify that this is still an issue?
With older npm versions it might help to run `npm update --depth=1000` to really update all deps (I do favor just using the newest version of npm though)

**Comment by wswoodruff** [comment]
Deps are up to date
