### ISSUE TITLE
How to get the request object into a helper

### ISSUE THREAD

**Issue by lenovouser** [hapijs/vision#103]
I am using vision with handlebars and want to get the request object into the helper. But at the moment there doesn't seem to be a way to do that, or am I wrong?

**Comment by calmdev** [comment]
I'm not sure about handlebars, but I feel like I've came across other hapi users asking the same question. I do know it doesn't natively support async helpers though. If you're open to using [DustJS](http://www.dustjs.com/) it's possible to access the request object rather easily. 

Example, `scope` helper to see if a currently authenticated user has access to something:
```js
'use strict';

function scope(chunk, context, bodies, params) {

  const can = context.resolve(params.can);
  const user = context.get('user') || context.get('request').auth.credentials.user;
  const scopes = user.scope;
  return scopes.includes(can);
};

module.exports = scope;
```

Then within your view template(s):

```html
{@scope can="website:edit"}
  can edit websites.
{:else}
  missing the website edit scope.
{/scope}
```

**Comment by wswoodruff** [comment]
@lenovouser Please see #112 and pass information from the request to your templates that way.
