### ISSUE TITLE
Question: Is there a way to modify output html before sending?

### ISSUE THREAD

**Issue by jgallen23** [hapijs/vision#104]
We are transitioning from http to https and I want to have a fail-safe in place where we replace cdn http urls with https in our views before getting sent out.  Is there a way to get access to the output html?  I tried onPreResponse, but I couldn't find anyway to access the html in the `request.response` object

**Comment by marcuspoehls** [comment]
Hi @jgallen23, maybe the following idea is an option: render the template first, replace your links within HTML from `http` to `https` and than reply the updated HTML in reply. For a single route, the code code look like this:

```js
server.route({
  method: 'GET',
  path: '/',
  handler: function(request, reply) {
    var data = {
      title: 'Hapi Render Views',
      message: 'Wohoo \\o/ Your view has been rendered successfully! boyahh'
    }

    request.render('index', data).then(function(view) {
      reply(view)
    })
  }
})
```

Hope you make progess on your issue.

Did you already solve it in another way?
