### ISSUE TITLE
access to server inside helper?

### ISSUE THREAD

**Issue by jgallen23** [hapijs/vision#112]
When using helperPaths, is there any way to access the server object inside the helper?  I need some settings that are set on `server.settings.app` inside the helper

**Comment by sholladay** [comment]
I think you could technically do this.

**In the handler:**
```js
reply.view('my-view', {
    some : 'foo data',
    server : request.server
});
```

**In the view:**

```handlebars
{{someHelper server}}
```

I would personally try to avoid giving such a powerful object to a helper. Seems risky, particularly if the helper comes from or includes 3rd party code.

**Comment by wswoodruff** [comment]
@jgallen23 pass in the exact properties you're looking to use from the `server` object to your template, `server.settings.app.x.x` -- try to be as specific as possible, using the method @sholladay described above
