### ISSUE TITLE
`request.render` does not pass the request to the context function

### ISSUE THREAD

**Issue by rubennorte** [hapijs/vision#115]
I that rendering a template with `request.render` is supposed to be equivalent to doing so with `reply.view` but the prior doesn't send `request` to the `context` function configured in `server.views`.

```javascript
server.views({
  ...
  context: request => request.app.someProperty
});
```

Using `reply.view` works fine but with `request.render` `request` in undefined.

Edit: I needed this to use `request.render` as a workaround for #106

**Comment by rubennorte** [comment]
I just saw a test that specified that was the expected behaviour:

```javascript
it('does not pass the request to the global context function (request)', (done) => {
```

Is there any reason for that?

**Comment by wswoodruff** [comment]
This is a great question, honestly I don't know why `request.render` doesn't pass the `request` to the global context. @hueniverse?

**Comment by hueniverse** [comment]
Been far too long for me to recall.

**Comment by devinivy** [comment]
Followed the blame and found this: https://github.com/hapijs/vision/pull/81.  I can't see any particular reason, but @jagoda definitely is clear in the docs and tests about the behavior.  It might just be for consistency between `server.render()` and `request.render()` versus `h.view()` and the view handler.

**Comment by wswoodruff** [comment]
Interesting, does anyone have thoughts on if these 3 should act the exact same? Assuming the `server`, `request`, and `h` all have the same realm when `render()`ing or calling `view()`?

**Comment by wswoodruff** [comment]
I'm currently focusing on a larger update in #135, and can get to this after I brush that up and it gets merged

**Comment by wswoodruff** [comment]
Yo @rubennorte I've got a PR for this here: #140
