### ISSUE TITLE
Is there a programmatic way to clear template cache?

### ISSUE THREAD

**Issue by TabishRizvi** [hapijs/vision#120]

**Comment by wswoodruff** [comment]
@TabishRizvi What's your use-case for this??

**Comment by bricss** [comment]
Check this page https://hapijs.com/tutorials/views for `isCached` option
```javascript
server.views({
    engines: {
        // setup engine
    },
    isCached: false
});
```

**Comment by wswoodruff** [comment]
Oh, is your problem solved by #132? I just merged that and pushed it to vision `v5.2.0`

**Comment by wswoodruff** [comment]
@bricss ^^ As of 5.2.0 if `isCached` is false, Vision will reload templates and helpers when it's served (on every page refresh) =) Please let me know if you were experiencing a different issue

**Comment by wswoodruff** [comment]
@bricss Note, using Vision `5.x.x` requires you upgrading your API to hapi `v17`

**Comment by wswoodruff** [comment]
@bricss ping on this issue

**Comment by bricss** [comment]
@wswoodruff guess it can be closed, working like a charm for me 😁 👍

**Comment by wswoodruff** [comment]
Glad to hear 👍

**Comment by axpro** [comment]
I think it would pe helpful to have a method to clear cached templates. For example we fetch some layouts from an external api and write them to disk before vision initializes but we have to restart the hapi servers on every layout change.

If restarting the servers would be a problem we could fetch the templates to memory and compile the templates manually, without vision.

**Comment by wswoodruff** [comment]
Ok I can look into this, I could expose a function on the manager maybe.
I'm definitely open to PRs too @axpro!

**Comment by axpro** [comment]
I'll try to find some spare time to look over the code to not miss anything and I'll make a PR.
Thanks
