### ISSUE TITLE
Get the template directory

### ISSUE THREAD

**Issue by sholladay** [hapijs/vision#122]
## Use case

I made an [error transformation](https://github.com/hapijs/hapi/blob/master/API.md#error-transformation) plugin, [hapi-error-page](https://github.com/sholladay/hapi-error-page).

Currently, my plugin calls `h.view('error', context)` when it wants to render the view. This works great in that the user's Vision options will be respected. They must create a view like `error.html` (for example) themselves, but their `relativeTo` and `path` options give them flexibility for where it must live.

I want to improve on this, though. I want to ship a fallback template with my plugin _without_ masking their own if it exists. So I need a way to add a directory to `path` for a given response.

## Details

I know that Vision allows `path` to be an array and that I can override `path` in `h.view()`. That is nice because one way to accomplish what I want would be to coerce the existing `path` to an array and then push my plugin's template directory to the end of it and provide that to `h.view()`.

Unfortunately, I don't know a good way to retrieve the existing `path`, only how to override it.

I did find a private and undocumented way using `request.server.realm.plugins.vision.manager._engines.html.config`:

https://github.com/sholladay/hapi-error-page/blob/38b688e588b028c1feeb4934c0ef09c011376170/index.js#L37-L40

However, that has multiple drawbacks:
 - It is using a private field, `_engines`
 - It is using undocumented data structures
 - It ties the user down to `html`, which seems unnecessary
 - It is very verbose
 - I'm not sure if it is the _correct_ place to consult for this data (i.e. not sure how route config plays into this, etc)
 - Seems like Vision should provide either a method to retrieve the path that should be used _or_ a method to coerce it to an array and add to it for the current response (e.g. `reply.views.addToPath('foo'))`

**Comment by wswoodruff** [comment]
Been thinking about this, and the use-case. Would this problem be solved by allowing for appending to a list of `defaultPath`s? If you could pass the `defaultPath` option to the views manager and it would append it to any existing ones in an array, would that solve the problem?

**Comment by wswoodruff** [comment]
I'm also _considering_ the pro's and cons of making a public getter to grab ahold of the `manager`. If you could grab the manager and see the path set, (assuming the manager has path as a public prop) then you could provide your default that way.

2 different approaches, thoughts?

**Comment by wswoodruff** [comment]
In addition, the `defaultPath` option would allow for catching handlers and partials! If that functionality was available, plugins could be made that provided helpers and partials to the user

**Comment by sholladay** [comment]
It sounds like those might work. Although I'm a bit unclear on the difference between `path` and `defaultPath`. I would expect, from the name, for `defaultPath` to only take effect if `path` is not set, I think. But you're saying I could ensure a directory within my plugin is _always_ appended to `path`, right? If so, then that should work. Note that I don't want to assume the user has `error.html` just because they have a `path` set, so I need to always append.

As for reading the end user's `path` from the manager, that should totally work. It's basically what I'm doing in the commented out code I linked to above, except I only figured out how to read it from the HTML engine - it should really be engine agnostic. If I understand you correctly I would simply update that code to use...

```js
request.server.realm.plugins.vision.manager.thePathConfig
```
... where `thePathConfig` is the hypothetical property. That is still pretty verbose, but I'm okay with that and it's definitely better than my existing hacky solution. 👍

**Comment by wswoodruff** [comment]
In the latter case , I was suggesting a less `verbose` getter for the manager, in _addition_ to the manager providing a getter for the path

**Comment by wswoodruff** [comment]
I still haven't figured out what that would look like yet. Currently, the only way to grab the manager is the return value of `server.views({ ... });` (views manager options). I'm not sure where to add a getter yet that would cover all places where you'd be rendering. `server.render`, `request.render`, `h.view`

**Comment by sholladay** [comment]
I think it would be unwise for me to call `server.views({ ... })` from my plugin. It will have to be something appropriate for an `onPreResponse` handler. At the moment I'm using `reply.view()`.

**Comment by wswoodruff** [comment]
I think the best solution for this would be making manager a class and exposing some properties / methods on it, could also solve #120

Plan would be to provide 2 new server extensions to add the manager to server and request (plugin-specific managers)
