### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by hueniverse** [hapijs/vision#123]
@nlf this module is no longer actively maintained. Need to find someone new to take over.

**Comment by wswoodruff** [comment]
I'm interested! Shall I tackle a couple issues as a smoke test??

**Comment by nlf** [comment]
please do!

**Comment by nlf** [comment]
reviews of existing pull requests would also be great

**Comment by wswoodruff** [comment]
@nlf A decent amount of the issues can be closed, I can go through some more of them soon but I went through the PR's =)

**Comment by hueniverse** [comment]
@wswoodruff you should have access rights once to accept the org invite. Feel free to change ownership info. When you are ready to publish, I can give you npm access rights.

**Comment by futurechan** [comment]
Doesn't lout depend on vision? If so, how will it be impacted by this?

**Comment by wswoodruff** [comment]
Should be fine -- I have an open line of communication with @Marsup in the `hapi hour` Slack! =P

**Comment by futurechan** [comment]
Awesome. Thanks.
