### ISSUE TITLE
path supposedly can be an array but can it really?

### ISSUE THREAD

**Issue by steevhise** [hapijs/vision#125]
I'm trying to have template files in multiple places.  But setting server.views path option to an array, such as 
`path: ['./src/views', './build/views']`\
Which the docs seem to say is allowed (and indeed in the code the Joi schema seems like it IS allowing it).
But, when all is said and done it seems to only be looking in the directory that is the  first item in the array.  Can anyone confirm this? And is that a bug or do the docs just mislead?

**Comment by Marsup** [comment]
https://github.com/hapijs/vision/blob/master/lib/manager.js#L438-L456

Doesn't look like what you described at all, it stops on the 1st found file.

**Comment by steevhise** [comment]
Confirmed. Sorry. The problem is actually that I assumed the path setting would be passed on to the template engine for use in looking for included partials, but apparently at least the engine I'm using (swig) doesn't work that way.
