### ISSUE TITLE
Update for Hapi 17?

### ISSUE THREAD

**Issue by tanepiper** [hapijs/vision#129]
Will Vision be updated for Hapi 17 (hapijs/hapi#3658)?

**Comment by marcuspoehls** [comment]
It is already, vision `5.1.0` is available via NPM and compatible with hapi v17

**Comment by tanepiper** [comment]
@marcuspoehls The docs don't seem to reflect this though. The API still shows the reply method which is removed.

Are you adding this to the `h` object now? Do we just return the view value?

**Comment by marcuspoehls** [comment]
@tanepiper ah, I see. Sorry for being too direct and kind of to the point, not asking what you’re missing.

The actual setup of `vision` is the same, you’re still configuring `server.views`
To render a view from your route handlers, use `h.view(template, data, options)`.

Does this help you?

**Comment by wswoodruff** [comment]
@tanepiper I plan on updating the docs and tests sometime this week

**Comment by tanepiper** [comment]
@marcuspoehls Great, thanks :)

**Comment by marcuspoehls** [comment]
@tanepiper Sure! You're welcome :)
