### ISSUE TITLE
Vision 5.x.x does not work with hapi 16.x.x

### ISSUE THREAD

**Issue by bakarydiarra** [hapijs/vision#134]
Hi,

I had the following issue today
[link](https://github.com/glennjones/hapi-swagger/issues/477)
I found that it was related to the version of vision that I was using.
When installing vision using the `npm install` command, the default version is 5.1.0 which is not compatible with the HAPI version 16.6.2. I am not a node expert but I expected npm to take care of the dependencies versioning issues. However I had to downgrade vision to 4.0.0 myself to make it work.

Regards

**Comment by wswoodruff** [comment]
hapi modules are upgrading to new major versions supporting hapi v17's breaking changes
For hapi v16 please use vision `4.x.x`

If there are any specific requests to support new features with hapi v16, please create an issue -- also, I'd accept a PR of course =)

**Comment by wswoodruff** [comment]
I updated the README, added a note under `Usage`

**Comment by bakarydiarra** [comment]
@wswoodruff Thank you for the quick answer.
