### ISSUE TITLE
Getting property 'register' of undefined in vision and handlbars in node.js

### ISSUE THREAD

**Issue by Aakash-DD** [hapijs/vision#147]
//Vision templates
server.register(require('vision'),function (err) {
   if(err){
       throw err;
   }
   server.views({
       engines:{
           html:require('handlebars')
       },
       path:__dirname+'/views'
   });

});

And packages are --------------------------------------------------->>>

"dependencies": {
    "handlebars": "^4.0.11",
    "hapi": "^16.6.2",
    "inert": "^4.2.1",
    "vision": "^5.3.2"
  }
}

**Comment by Marsup** [comment]
You're using a vision version that's made for hapi 17.

**Comment by Aakash-DD** [comment]
@Marshup which version should i use??

**Comment by Marsup** [comment]
Latest of version 4.

**Comment by Aakash-DD** [comment]
yes, it worked tnks, by the way
