### ISSUE TITLE
Twig engine doesn't like includes

### ISSUE THREAD

**Issue by rickerd** [hapijs/vision#148]
I like twig alot since you can output really nice things and extend templates.
but... it doesn't work in vision?

[1] "allowInlineIncludes" is not allowed..

Is this a known thing or never used for some reason?

**Comment by wswoodruff** [comment]
Can I please see the options you're passing to Vision?

**Comment by wswoodruff** [comment]
That seems like it could be a Joi error but I can't tell exactly. You can pass library-specific options in the compile function, see the Marko example here: https://github.com/hapijs/vision#marko

**Comment by wswoodruff** [comment]
@rickerd That seems like it could be a Joi error but I can't tell exactly. You can pass library-specific options in the compile function, see the Marko example here: https://github.com/hapijs/vision#marko

**Comment by wswoodruff** [comment]
@rickerd ping on this issue

**Comment by rickerd** [comment]
Closing for now. Not active used at work.

**Comment by wswoodruff** [comment]
Ok please lemme know more about your setup if you decide to re-open
