### ISSUE TITLE
Log errors instead of console.warn()

### ISSUE THREAD

**Issue by JSteunou** [hapijs/vision#165]
Should this lib use hapijs server log instead of console.log ? I found out that having some not formatted / controled log can be pretty annoying. Had a case when playing with cache invalidation (manager.clearCache)

**Comment by wswoodruff** [comment]
I'm actually not sure what to do about this one! Looking into it

**Comment by hueniverse** [comment]
No module should log errors to console.

**Comment by hueniverse** [comment]
Marked as breaking since the behavior is somewhat different (though no actual breakage).

**Comment by hueniverse** [comment]
Closed by 0b29418e9c2445e881357af2dee61194b1ab38f1
