### ISSUE TITLE
Add partials & helpers cache invalidation

### ISSUE THREAD

**Issue by JSteunou** [hapijs/vision#166]
There is a template cache invalidation, but when you have some several templates and you make intensive use of helpers & partials this is no use because changes are mostly done in partials and invalidation of templates do not reload partials.

Partials & helpers cache invalidation can be done by reloading those them partials & helpers once again. [_loadPartials](https://github.com/hapijs/vision/blob/master/lib/manager.js#L135) could be split in 2 to have a singular `_loadPartial` used by both `_loadPartials` and a new `clearPartialCache`

What do you think ?

**Comment by wswoodruff** [comment]
Hey @JSteunou ! The new function to clear template cache is for use while running on production -- For development, you can disable caching of templates and helpers by setting `{ ... isCached: false }` when passing options to Vision

**Comment by JSteunou** [comment]
Yup, but I wanted to play with cache invalidation in production too :) 

I cheated a little by using private method, but `viewManager._loadPartials(hbsEngine)` works for my purpose. I wanted to experiment hot deployment of just assets like hbs partials / helpers / templates...

**Comment by wswoodruff** [comment]
@JSteunou Does using private methods provide you with what you're looking for? What's your production situation where you need reloading of partials and helpers, etc.

**Comment by JSteunou** [comment]
I does the job I was looking for.

Hot reloading allows to deploy new *statics* files without restarting the service.

**Comment by JSteunou** [comment]
Got it no problem
