### ISSUE TITLE
How to unit test reply.view() ?

### ISSUE THREAD

**Issue by createthis** [hapijs/vision#170]
Hello,

I often have controller tests in my code. It's easy to test for the statusCode and search the result for a certain string. However, it would be nice to have an easy way to assert the view and params passed to the view. For example:

```js
let somedata = {
  stuff: 'I contain stuff',
}
reply.view('path/to/view', {
  title: 'Some View',
  data: JSON.stringify(somedata)
});
```

To test this using `should.js`, I can do:

```js
let response = await server.inject(request);
should.equal(response.statusCode, 200);
response.payload.should.not.containEql('Access Denied');
```

But how would I assert that the view is `path/to/view` and that the view received a `data` attribute containing the string `'{"stuff": "I contain stuff"}'`?

**Comment by wswoodruff** [comment]
@createthis When using the [toolkit](https://hapijs.com/api#response-toolkit) you could monkey patch `request. generateResponse`, save the arguments and verify them that way

**Comment by wswoodruff** [comment]
@createthis any update on your issue?

**Comment by createthis** [comment]
I've kept this issue open in a chrome tab for 5 days because I wanted to try your suggestion but didn't have time. One moment. I have a second now. I'll see what I think about it.

**Comment by createthis** [comment]
@wswoodruff Ok, how would that work? I tried this:

```js
      let generateResponse = () => { console.log(arguments); }
      request.generateResponse = generateResponse;
      let response = await server.inject(request);
```

And I get this error:

```js
ValidationError: {
  "method": "GET",
  "url": "/myurl",
  "payload": {},
  "authority": "localhost:0",
  "generateResponse" [1]: function generateResponse() {\n                console.log(_arguments);\n              }
}

[1] "generateResponse" is not allowed
```

Can you provide an example?

**Comment by devinivy** [comment]
You can find the template and context information on `request.response.source`!
```
const { request } = await server.inject('/docs/boilerplate');
const { template, context } = request.response.source;
```

**Comment by createthis** [comment]
@devinivy is `response.source` only in newer versions? I do:

```js
      let response = await server.inject(request);
      const { template, context } = response.response.source;
      console.log('template=',template);
      console.log('context=',context);
```

And I get:

```js
     TypeError: Cannot read property 'source' of undefined
```

**Comment by devinivy** [comment]
I believe that property goes back more than a couple major vesions of hapi.  There is a slight issue in your code:
```
let response = await server.inject(request);
const { template, context } = response.response.source;
// versus
const { request } = await server.inject(request);
const { template, context } = response.response.source;
// which is similar to
const res = await server.inject(request);
const { template, context } = res.request.response.source;
```

**Comment by createthis** [comment]
@devinivy you're right! Also, this is exactly what I was looking for. This is perfect. Thank you!
