### ISSUE TITLE
Default context object doesn't populate views

### ISSUE THREAD

**Issue by geuis** [hapijs/vision#34]
Related to this https://github.com/hapijs/hapi/issues/2537.

From my testing, internals.handler doesn't get called when reply.view is called from a handler. So the default context object is not passed through.

**Comment by jagoda** [comment]
You are correct that `internals.handler` is not used with custom route handlers and @arb's comments about default attributes only apply to the [`view` handler](https://github.com/hapijs/vision#the-view-handler). However, the 'global' view context (without the additional default values) is still available to `reply.view()` via [this](https://github.com/hapijs/vision/blob/master/lib/manager.js#L271-283). In any case, the answer to your original question is that there are no default values on the context object for custom route handlers other than what is configured via the ['context' option](https://github.com/hapijs/vision#serverviewsoptions).

**Comment by geuis** [comment]
Thanks for the confirmation. I ended up writing a plugin that allows you to configure properties to be added to all requests. I'll update this issue with it in a while.

**Comment by jagoda** [comment]
@geuis were you able to work out what you needed? Is there anything else you need from me?

**Comment by geuis** [comment]
@jagoda I think that's it.
