### ISSUE TITLE
Vision 2.0.1 installing joi 5.1.0 instead of 6.x.x

### ISSUE THREAD

**Issue by toymachiner62** [hapijs/vision#35]
I have a couple of apps that when I deploy to a server, hapi 8.8.0 is installed which has vision 2.x.x as a dependency and installs vision 2.0.1. Vision 2.0.1 has joi 6.x.x as a dependency, but it installs joi 5.1.0. 

How is this possible? I have 2 different apps on 2 different computers which deploy to 2 different servers which completely different setups.

**Comment by Marsup** [comment]
Which version of npm are you using ?

**Comment by toymachiner62** [comment]
1.4.28

**Comment by Marsup** [comment]
You'd better use 2.x and never go back :)

**Comment by toymachiner62** [comment]
What's the best way to install 2.x?

Also every time I update my node version am I going to have to re-install npm 2.x?

Is there a specific version of node that ships with npm 2.x?

**Comment by toymachiner62** [comment]
Ok I do have one environment that is working. 

A weird thing I noticed is that on my environment that is working, it also has hapi 8.8.0 -> vision 2.0.1 but there is no node_modules folder in /vision

The way i build this app is I build locally including an `$ npm install` and then rsync my files to my server My rsync command didn't contain the `-r` option so it was leaving /vision/node_modules at version 5.x.x and i'm guessing my recent `$ npm install` updated hapi which probably updated vision which has an updated version of joi and since rsync didn't delete vision/node_modules there was a dependency discrepancy.
