### ISSUE TITLE
Nested Layouts

### ISSUE THREAD

**Issue by farwey** [hapijs/vision#41]
Is it possible to have nested layouts? For example, there would be a "master" layout that contains site-wide HTML (e.g. - global header, etc.) and a section-specific layout that contains HTML shared within a certain section of the site. 

An arbitrary example would be a "user settings" layout. The settings layout would contain common elements shared between each settings page, such as a menu for the settings sections. Would it be possible to render a specific settings page, such as "profile settings", into a settings layout that would then render into the master layout?

**Comment by jagoda** [comment]
`vision` itself does not provide any functionality for nested layouts (just basic layouts). However, several of the templating engines that are supported by `vision` provide features that should allow you to do very similar things. For example, [handlebars](http://handlebarsjs.com/) provides [partials](http://handlebarsjs.com/partials.html) that allow you define reusable chunks of content and [nunjucks](https://mozilla.github.io/nunjucks/) supports template inheritance (which is the closest thing I can think of to what you are asking about). There are basic examples for all of these in the `examples` folder.

**Comment by jagoda** [comment]
@farwey does this info address your question adequately? Do you have any more issues or concerns?
