### ISSUE TITLE
Vision Registration Failing?

### ISSUE THREAD

**Issue by 58bits** [hapijs/vision#52]
Hi there - upgrading to hapi v9.0.0, and have added the vision dependency, as well as what I thought was the correct require statement during plugin registration, but the application is failing with:

```
server/web/index.js:53
    server.views({
           ^
TypeError: undefined is not a function
```
Here's a Gist to the complete application setup... 

https://gist.github.com/58bits/12e3a8380327062a762b

Is there anything obvious wrong here?

@hueniverse any ideas?

**Comment by hueniverse** [comment]
It's a known bug. Because you have one plugin registering another, the `server` object the plugin gets doesn't get updated with the new methods. If you move vision to the glue file for now, it should work fine.

See https://github.com/hapijs/hapi/issues/2727

**Comment by 58bits** [comment]
@hueniverse - okay - thanks!

**Comment by jagoda** [comment]
Closing since the root issue is with hapi and not with vision.
