### ISSUE TITLE
Can I register different view engines for different connections?

### ISSUE THREAD

**Issue by johanalkstal** [hapijs/vision#53]
As described in this SO question I made,

http://stackoverflow.com/questions/32445904/can-i-have-different-view-engines-for-different-hapi-connections

Is it possible to create Hapi connections and have each one use Vision and register different view engines?

**Comment by Marsup** [comment]
Register vision once at the server level and you can indeed have different view engines, it's even possible to have different view engines on the same connection (per plugin).

**Comment by johanalkstal** [comment]
Oh, so you don't register vision with each connection, but with the server?

And then when setting up the connections you can call `server.views()` for each connection?

Each call to `server.views()` will register additional engine combinations?

Even if the engine is the same for the connections (for instance both connections would use handlebars)?

**Comment by Marsup** [comment]
> Oh, so you don't register vision with each connection, but with the server?

Yes, plugins adding decorations on the server usually don't support being registered multiple times.

You can register multiple engines in a single call or in multiple.
I think you can register the view engine on the server as well so it's global to all connections.

**Comment by johanalkstal** [comment]
Would you mind showing a working example?

I'm trying with the following code,

```
server.register(require('vision'), function (err) {
    if (err) { throw err; }
  });

  var userConnection = server.connection({
    host: options.host,
    port: options.port,
    labels: ['user']
  });

  var adminConnection = server.connection({
    host: options.host,
    port: options.port + 1,
    labels: ['admin']
  });

userConnection.views({
    engines: {
      hbs: require('handlebars')
    },
    path: Path.join(__dirname, 'user-server', 'templates')
  });

adminConnection.views({
    engines: {
      hbs: require('jade')
    },
    path: Path.join(__dirname, 'user-server', 'templates')
  });
```

When it gets to the second `.views()` call, I get an error

`Error: Cannot set views manager more than once`

**Comment by Marsup** [comment]
Oh ok, maybe I was wrong on the multiple calls, I thought each connection had a different realm. Then plugin it is. FWIW it's bad to assume plugins can be registered synchronously like you did.

**Comment by johanalkstal** [comment]
How would a plugin approach work differently?

You still register `vision` with the server, then you pass `server` to the `register` method of the plugins, right?

So would that not yield the same error as the above, because you're still trying to set the view manager more than once on the `server` object?

Sorry if I'm being ignorant, I'm new to the Hapi ecosystem.

**Comment by Marsup** [comment]
A plugin has its own realm, vision takes advantage of that and can scope its view engine to only that plugin.

**Comment by Marsup** [comment]
To add on that, only routes declared within the same plugin will be able to use that view engine of course.

**Comment by johanalkstal** [comment]
Okay, I got it working using plugins and a little bit of glue. :)

Thanks for your help!

**Comment by kuongnp** [comment]
Hi all bro, you can show code example using core hapi todo set views engines for backend and fronend connection,  if can't , how using glue to do it. Thanks all
