### ISSUE TITLE
Global context with request argument

### ISSUE THREAD

**Issue by g6123** [hapijs/vision#59]
When global context was first suggested in #4, functions that generate context could have a `request` argument. Like this :

```js
server.views({
  context: function (request) {
    return {
      version: '1.4.5',
      date: Date.now(),
      id: request.id
    }
  }
});
```

But it is not actually implemented now, and I think that idea is quite essential in many cases of developments.

**Comment by jagoda** [comment]
This was considered in the original implementation (see #6). However, it's not as simple as it may seem. As the discussion in #6 indicates, the `request` object is usually available in the handler that is preparing the context so this is usually not necessary. Could you elaborate on your specific scenario to help me understand why you need this?

**Comment by g6123** [comment]
I'd like to make specific session data globally accessible in every template I use. So, now I'm using solution below, and it works well anyway.

```js
server.ext('onPreResponse', function(request, reply) {
	var response = request.response; 

	// request.username has been set by other plugin
	var globalContext = {
		username: request.username
	};

	if(response.variety === 'view') {
		response.source.context = _.extend(
			globalContext, (response.source.context || {})
		);
	}

	reply(response);
});
```
I still hope vision supports this by cleaner way, but I understood why it's quite complicated.. Thanks.
