### ISSUE TITLE
modifying the views object before compilation

### ISSUE THREAD

**Issue by phitran** [hapijs/vision#60]
Prior to ```v3.0.0``` we could modify the views object during the preResponse event. Moving the compilation step earlier in the request lifecycle no longer allows this. Any ideas on getting this work in ```v3.0.0```?

Example:

template files:
```
./server/views/desktop/index.ejs
./server/views/mobile/index.ejs
```

views object:
```javascript
views: {
    engines: {
        'ejs': ejs
    },
    relativeTo: './server/views'
};
```

onPreResponse:
```javascript
if ( response.variety === 'view' ) {
    var userAgent = request.plugins.scooter;

    if ( mobileIdentifier( userAgent ) ) {
        request.response.source.options = { path: 'mobile' };
    } else {
        request.response.source.options = { path: 'desktop' };
   }
};
```

**Comment by hueniverse** [comment]
The template is being compiled but not the actual view. If this is not the case, it's a bug. You should be able to change the context all the way to onPreResponse.

**Comment by phitran** [comment]
Thanks for the correction .You're right, the template that is being compiled earlier is causing my issue. I should of stated that I am receiving the bad implementation error: ```View file not found:... Locations searched: ./server/views/```

We are changing what template that is being compiled based on the userAgent. Do you have a recommendation on how to achieve this? Worse case we could stick with ```v2.0.1```

**Comment by hueniverse** [comment]
That's a new use case, messing with the template. You should just return a whole new response. What I would do is pass along a simple context object and in onPreResponse return a view with the request.response object as context.

**Comment by phitran** [comment]
Thanks for your help on this!

**Comment by hueniverse** [comment]
Did it solve your problem?

**Comment by phitran** [comment]
Had to postpone the changes/updates. But I will post here again once we get back to it very soon.

**Comment by phitran** [comment]
it's been a while.. "very soon" :expressionless:, ha.

We finally got around to implementing your suggestion and I am happy to report it solved our problem. We are now using the latest vision!

Thanks again!
