### ISSUE TITLE
Example code out of date. Can we PR an update?

### ISSUE THREAD

**Issue by nelsonic** [hapijs/vision#62]
https://david-dm.org/hapijs/vision#info=devDependencies&view=table
[![devDependency Status](https://david-dm.org/hapijs/vision/dev-status.svg)](https://david-dm.org/hapijs/vision#info=devDependencies)

**Comment by jagoda** [comment]
Are you asking if you can submit an update or if somebody else can? I'd be happy to take a PR from anybody. Just be sure to check that all of the examples still work and to fix anything that breaks.
