### ISSUE TITLE
Jade problems / hanging

### ISSUE THREAD

**Issue by vizo** [hapijs/vision#70]
When i visit localhost:3000 template shows up but then if i change template and hit refresh, template shows up without changes, but process hangs for some time (depends how many times i hit refresh). Using same version of jade in express works.

Even if i copy sample from vision/examples/jade/index.js it is same ....

Did i miss something?

I have the following setup:
```javascript
const Hapi = require('hapi');
const Hoek = require('hoek');
const jade = require('jade');
const vision = require('vision');
const server = new Hapi.Server();

server.connection({
  host: 'localhost', 
  port: 3000
});

  server.register(vision, (err) => {
    // Hoek.assert(!err, err);
    
    server.views({
      engines: {
        jade: jade
      },
      relativeTo: __dirname,
      path: 'views',
      compileOptions: {
        cache: true,
        pretty: false,
        debug: true,
        compileDebug: true
      }
    });
  });

  server.route({
    method: 'GET',
    path: '/sl',
    config: {
      id: 'root.sl',
      handler: function (request, reply) {
        reply.view('services');
      }
    }
  });

  // Start the server
  server.start((err) => {
    if (err) {
      throw err;
    }
    console.log('Server running at:', server.info.uri);
  });

```
Vision version: 4.0.1
Hapi version: 11.1.4
Jade version: 1.11.0
Node version: v5.3.0

**Comment by vizo** [comment]
Oh i see, i missed out option server.views({..., isCached: false, ... }).
I am new to Hapi. I was figuring this out 4h.

**Comment by jagoda** [comment]
I have not been able to reproduce this in my environment. However, you seem to reference using the cluster module in your comments. Is it possible that the process hanging is actually related to your use of the cluster module and not to vision/jade?

**Comment by jagoda** [comment]
Any thoughts?
