### ISSUE TITLE
Send helper parsing error to user

### ISSUE THREAD

**Issue by mtharrison** [hapijs/vision#73]
If you include a helper in the helpers directory and it cannot be loaded (i.e. `require()` throws), [the error is lost](https://github.com/hapijs/vision/blob/master/lib/manager.js#L260). It would be useful to see some kind of error here, perhaps you just made a simple syntax error that needs fixing.

**Comment by jagoda** [comment]
Allowing the error to propagate could break some existing users. For example, some users may have files in the helpers directory that aren't actually helpers (ex. documentation). What do you think about adding a configuration option that would allow you to opt in to this behavior?

**Comment by mugli** [comment]
I also faced this. I don't think silently discarding errors is a good idea. We had a hard time figuring out what was wrong, initially we even thought it might be related to ES6 support in node, since `const` and `var` worked but `let` doesn't, and fails silently (mentioned in nodejs/node#4618).

**Comment by mtharrison** [comment]
Making it configurable is definitely better than nothing but I'm not sure how useful it would be. If you can find the option, knowing you need it, you'd probably just find your bug too.

How about a warning instead of an exception?

**Comment by jagoda** [comment]
Ah, yup, makes sense. I think that should be doable.
