### ISSUE TITLE
Q: Are template files cached?

### ISSUE THREAD

**Issue by abeninskibede** [hapijs/vision#78]
Hey guys,

I have a plugin which uses handlebars as view engine.
```
    plugin.views({
      engines: {
        html: require('handlebars')
      },
      path: __dirname
    });
```
When I make changes to the login.html file I need to restart the server in order to force hapi to pick my changes.

I have globally registered Vision for my server and this is my route:
```
    plugin.route({
      method: 'GET',
      path: '/login',
      handler: (req, reply) => {
        reply.view('login', { title: 'Login page via handlebars' });
      },
      config: {
        auth: false
      }
    });
```
Is there a way to disable this while developing?

**Comment by mtharrison** [comment]
See `isCached` option: https://github.com/hapijs/vision/blob/master/API.md#serverviewsoptions

**Comment by abeninskibede** [comment]
Cool 10x!
