### ISSUE TITLE
ejs template engine options is not working

### ISSUE THREAD

**Issue by zzbo** [hapijs/vision#83]
Hello, I pass a property `compileOptions` as following, but the ejs template always cache compile result, it's worng way?

```js
server.views({
        engines: {
            ejs: require('ejs')
        },
        relativeTo: __dirname,
        path: 'Templates',
        compileOptions: {
            cache: false
        }
});
```

**Comment by Marsup** [comment]
You forgot that vision itself caches the compiled version, see `isCached` in the api docs.

**Comment by zzbo** [comment]
@Marsup  thank you for your help, it is solved.
