### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by gergoerdosi** [hapijs/vision#87]
```
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
```

**Comment by mtharrison** [comment]
Unfortunately there are no stable releases of Pug yet on npm afaik.

**Comment by cuihp** [comment]
how to update?

**Comment by AdriVanHoudt** [comment]
@cuihp is there a stable release of Pug on npm now?

**Comment by wswoodruff** [comment]
No idea what's going on with these releases: https://github.com/pugjs/pug/releases -- it looks like [v1.11.0](https://github.com/pugjs/pug/releases/tag/1.11.0) is the latest stable release -- does anyone have experience with this version? @gergoerdosi?

**Comment by wswoodruff** [comment]
Looks like `pug` is close to v2, I might wait for that release to bring it in. In the meantime I can get a start on the latest release and fix issues once v2 is stable

**Comment by wswoodruff** [comment]
Pug is already implemented: https://github.com/hapijs/vision/blob/72480f8eb8dd65571b7ba25ef0eb4d914a058644/test/manager.js#L462-L478
