### ISSUE TITLE
Include global handlebars layout for use in plugin

### ISSUE THREAD

**Issue by failpunk** [hapijs/vision#90]
I have an app using handlebars as the template engine and I want to register a series of plugins (user registration / auth) that render within the root apps handlebars layout.  The plugin will only serve the user form.

Trying to serve a layout from the parent app throws this error:
`[error] message: View paths cannot lookup templates outside root path (path includes one or more '../') stack: Error: View paths cannot lookup templates outside root path (path includes one or more '../')`

In this case I am trying to pass the path of the root applications layout file via the plugin options.

How can I serve a handlebars template with a form via a hapi plugin but have it render within the root applications layout?

**Comment by failpunk** [comment]
To follow up if I set `allowInsecureAccess: true` in my plugin I can then access the parent apps layout.

**Comment by jagoda** [comment]
👍
