### ISSUE TITLE
manually registering a helper

### ISSUE THREAD

**Issue by jgallen23** [hapijs/vision#93]
is there any way to get access to the view manager so I can register a helper?

**Comment by devinivy** [comment]
Yes, there are two ways.  The most straightforward way is to use the manager returned from `server.views()`, like [this](https://github.com/hapijs/vision/blob/5747651957134458252750f1bef5a5a12c600276/test/index.js#L813-L833).  The lesser-doc'd way is to access that same manager on the realm of the plugin that called `views()` (e.g. `server.realm.plugins.vision.manager`).  I can't speak to whether that's technically in the public API– @jagoda?

**Comment by jagoda** [comment]
The preferred way to do this is to use the return value of `server.views()`. While the realm approach will work, my understanding of realms is that they are primarily used for plugin-specific state. I don't consider this to be part of the public API and it should not be relied upon.
