### ISSUE TITLE
Process for adding to /examples ?

### ISSUE THREAD

**Issue by nelsonic** [hapijs/vision#99]
Hi @jagoda,
We would like to add a Riot.js http://riotjs.com/ example to Vision.
(_firstly, would a Pull Request with such an example be accepted?_)
Would the JSX (react) Pull Request: https://github.com/hapijs/vision/pull/36 be a good example to follow?
_Thanks!_

**Comment by jagoda** [comment]
Yes, that is a fine example to follow and a PR would be most welcome.

**Comment by nelsonic** [comment]
@jagoda thanks for confirming! I'm working on it... Want to show a _simple_ as well as an "isomorphic" example... 😉
